
#ifndef __MCK__COMPILER_VC2015_MINI_INCLUDE_UCRT_CORECRT_WSTDIO_H__
#define __MCK__COMPILER_VC2015_MINI_INCLUDE_UCRT_CORECRT_WSTDIO_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "corecrt.h"
#include "corecrt_stdio_config.h"

#endif