
#ifndef __MCK__COMPILER_VC2015_MINI_INCLUDE_UCRT_MEMORY_H__
#define __MCK__COMPILER_VC2015_MINI_INCLUDE_UCRT_MEMORY_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "corecrt_memory.h"

#endif