
#ifndef __MCK__COMPILER_GCC_4_INCLUDE_MACHINE__DEFAULT_TYPES_H__
#define __MCK__COMPILER_GCC_4_INCLUDE_MACHINE__DEFAULT_TYPES_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "VuxMock/_Compiler/gcc_4/include/glibc/limits.h"

#endif