
#ifndef __MCK__COMPILER_GCC_4_INCLUDE_MACHINE__TYPES_H__
#define __MCK__COMPILER_GCC_4_INCLUDE_MACHINE__TYPES_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "_default_types.h"

#endif