
#ifndef __MCK__COMPILER_VC2015_MINI_INCLUDE_SAL_H__
#define __MCK__COMPILER_VC2015_MINI_INCLUDE_SAL_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "ConcurrencySal.h"

#endif