
#ifndef __MCK__COMPILER_VC2015_MINI_INCLUDE_VCRUNTIME_STRING_H__
#define __MCK__COMPILER_VC2015_MINI_INCLUDE_VCRUNTIME_STRING_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "vcruntime.h"

#endif