
#ifndef __MCK__COMPILER_VC2015_MINI_INCLUDE_VCRUNTIME_H__
#define __MCK__COMPILER_VC2015_MINI_INCLUDE_VCRUNTIME_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "sal.h"
#include "vadefs.h"

#endif