
#ifndef __MCK_USR_INCLUDE_MACHINE__DEFAULT_TYPES_H__
#define __MCK_USR_INCLUDE_MACHINE__DEFAULT_TYPES_H__


//$$VUNIT(BEGIN,VMOCKADDGLOBAL)
//$$VUNIT(END,VMOCKADDGLOBAL)

#include "VuxMock/usr/include/limits.h"

#endif